### ISSUE TITLE
Problém v pojmenování souboru

### ISSUE THREAD

**Issue by revoke** [ondrakoupil/tools#1]
Při instalaci balíčku na Windows dochází k problému s vytvářením souboru aux.php a složky aux. Jejich názvy totiž obsahují nějaký prázdný znak, se kterými si Windows neporadí a composer háže chybu. 
Soubory pak ani nejdou běžným způsobem smazat z disku (je zapotřebí použít del "\\?\c:\path_to_file\aux.php", resp. rmdir). 
Takhle to vypadá, když ty soubory stáhnu z Linuxového stroje.
![image](https://user-images.githubusercontent.com/1552913/221083733-4ad1e550-6bda-49da-a7bf-fd54466c4a5c.png)

**Comment by ondrakoupil** [comment]
Zkuste to prosím teď s nejnovějším commitem, testy jsem přeorganizoval a aux.php úplně zrušil. 
Bohužel nemám dost dobře jak otestovat...

**Comment by revoke** [comment]
Ne, je s tím stále nějaký problém. Nicméně už se alespoň na disku nevytváří složka, co pak ani nejde smazat.

**PHP 7.4**
![image](https://user-images.githubusercontent.com/1552913/223075172-a86f49de-cc1f-4225-9138-fe50be80c80e.png)

**PHP 8.1**
![image](https://user-images.githubusercontent.com/1552913/223076654-01c9c974-6123-43cd-b7e2-bbb747fdab44.png)

**Comment by MichaelPavlista** [comment]
Ahoj,
problém je v tom, že název složky `aux` je na Windows do verze 11 rezervovaný.
Složku s tímto názvem není možné založit.

Díky tomu instalace balíčku na Windows, nebo Dockeru běžícím na Windows selže.

MR zde: https://github.com/ondrakoupil/tools/pull/2.
